titulo = input("Ingrese el titulo de un libro: ")
autor = input("Ingrese el nombre del autor: ")
print("Proporciona el titulo: ", titulo)
print("Proporciona el autor: ", autor)
print(titulo, " fue escito por ", autor)